import { ContentLayout } from "@/components/admin-panel/content-layout";
import { StockAddAutoGeneratedContainer } from "./stock-adder";
import { Navbar } from "@/components/admin-panel/navbar";

export default async function AddStockAutoGeneratedPage() {
  return (
    <>
      <Navbar title="Add Stock" />
      <StockAddAutoGeneratedContainer />
    </>
  );
}
